/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;
import Entidades.Incidente;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author Proyector
 */
public class FrameRegistrar extends javax.swing.JFrame {

private FrameVisualizar padre; 
private Incidente incidente;
 private boolean estoyEditando = false;
 public static List<Incidente> listaDeIncidentes;
  
 
 private String imagePath;
    /**
     * Creates new form RegistrarIncidente
     */
    public FrameRegistrar() {
        initComponents();
    }
    public FrameRegistrar(FrameVisualizar padre){
      initComponents();
      this.padre = padre;
     
      }

   

                                       
private void salir(){
      padre.setVisible(true);
      this.dispose();
    }


 




 public FrameRegistrar(FrameVisualizar padre, Incidente incidente) {
        initComponents();
        this.padre = padre;
        this.incidente = incidente;
        this.estoyEditando = true;
       // this.Registrar.setVisible(false);
        //this.jLabel9.setVisible(false);
        //lblTitulo.setText("Visualizar Cita");
        this.txtTipo.setText(incidente.getTipo());
        this.txtHora.setText(incidente.getHora());
        this.txtFecha.setText(incidente.getFecha());
        this.txtDescripcion.setText(incidente.getDescripcion());
        
//        cbEspecialidad.removeAllItems();
//        cbEspecialidad.addItem(cita.getEspecialidad().getNombre());
//        
//        cbFecha.removeAllItems();
//        cbFecha.addItem(GestorDeCitas.fechaDisponibles.get(cita.getFecha()));
//        
//        cbHora.removeAllItems();
//        cbHora.addItem(GestorDeCitas.horasDisponibles.get(cita.getHora()));
    } 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        btnCargarImagen4 = new javax.swing.JButton();
        btnCargarImagen3 = new javax.swing.JButton();
        lblImagen2 = new javax.swing.JLabel();
        btnCargarImagen2 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnCargarImagen = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        lblRegistrar = new javax.swing.JLabel();
        lblAñadir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 170, 160));
        jPanel1.add(lblImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 150, 150));

        btnCargarImagen4.setText("Añadir");
        btnCargarImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarImagen4MouseClicked(evt);
            }
        });
        jPanel1.add(btnCargarImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 70, 20));

        btnCargarImagen3.setText("Añadir");
        btnCargarImagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagen3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, 20));
        jPanel1.add(lblImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 170, 160));

        btnCargarImagen2.setText("Añadir");
        btnCargarImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagen2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 70, 20));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 160, 150));

        btnCargarImagen.setText("Añadir");
        btnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 70, 20));

        txtTipo.setBorder(null);
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 170, 30));

        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 170, 30));

        txtHora.setBorder(null);
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 170, 30));

        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 270, 250));

        lblRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarr.png"))); // NOI18N
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        lblAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadi.png"))); // NOI18N
        lblAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAñadirMouseClicked(evt);
            }
        });
        jPanel1.add(lblAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EditarIncidente.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(lblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 160, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAñadirMouseClicked
        // TODO add your handling code here:
        FrameRegistroPrueba pantallaRegistro = new FrameRegistroPrueba(this);  
        pantallaRegistro.setLocationRelativeTo(this); 
        pantallaRegistro.setVisible(true);
        
        
        this.setVisible(false);
    }//GEN-LAST:event_lblAñadirMouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:}
        salir();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        
    
      if (incidente != null) {
        // Actualizar el estudiante existente
        incidente.setTipo(txtTipo.getText());
        incidente.setFecha(txtFecha.getText());
        incidente.setHora(txtHora.getText());
        incidente.setDescripcion(txtDescripcion.getText());
        // Llama a un método en FrameEstudiantes para actualizar el modelo del JList.
        this.padre.actualizarInciden(incidente);
    } else {
        // Crear un nuevo estudiante
        String tipo = txtTipo.getText();
  String fecha = txtFecha.getText();
   String hora = txtHora.getText();
   String descripcion = txtDescripcion.getText();
        Incidente nuevoIncidente = new Incidente(fecha, tipo, descripcion, hora);
        nuevoIncidente.setTipo(txtTipo.getText()); 
        nuevoIncidente.setFecha(txtFecha.getText());
        nuevoIncidente.setDescripcion(txtDescripcion.getText());
        
        // Llama a un método en FrameEstudiantes para agregar el nuevo estudiante al modelo del JList.
        this.padre.agregarInciden(nuevoIncidente);
    }
    
    // Mostrar FrameEstudiantes nuevamente y cerrar FrameEstudiante
    this.padre.setVisible(true);
    this.dispose();
    
    
    
    
    
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnCargarImagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagen3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File  file = fileChooser.getSelectedFile();
            imagePath = file.getAbsolutePath();
            // Actualizar la etiqueta con la imagen seleccionada
            mostrarImagen3(imagePath);
        }
    }//GEN-LAST:event_btnCargarImagen3ActionPerformed

    private void btnCargarImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagen2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File  file = fileChooser.getSelectedFile();
            imagePath = file.getAbsolutePath();
            // Actualizar la etiqueta con la imagen seleccionada
            mostrarImagen2(imagePath);
        }
    }//GEN-LAST:event_btnCargarImagen2ActionPerformed

    private void btnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagenActionPerformed

        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File  file = fileChooser.getSelectedFile();
            imagePath = file.getAbsolutePath();
            // Actualizar la etiqueta con la imagen seleccionada
            mostrarImagen(imagePath);
        }
    }//GEN-LAST:event_btnCargarImagenActionPerformed

    private void btnCargarImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarImagen4MouseClicked
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File  file = fileChooser.getSelectedFile();
            imagePath = file.getAbsolutePath();
            // Actualizar la etiqueta con la imagen seleccionada
            mostrarImagen4(imagePath);
        }
    }//GEN-LAST:event_btnCargarImagen4MouseClicked

    
        private void mostrarImagen(String imagePath) {
        ImageIcon icon = new ImageIcon(imagePath);
    lblImagen.setIcon(icon);
    
}
    private void mostrarImagen2(String imagePath) {
        ImageIcon icon = new ImageIcon(imagePath);
    
    lblImagen2.setIcon(icon);
}
    
        private void mostrarImagen3(String imagePath) {
        ImageIcon icon = new ImageIcon(imagePath);
    
    lblImagen3.setIcon(icon);
}
    
           private void mostrarImagen4(String imagePath) {
        ImageIcon icon = new ImageIcon(imagePath);
    
    lblImagen4.setIcon(icon);
}
    
    
    
    
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnCargarImagen2;
    private javax.swing.JButton btnCargarImagen3;
    private javax.swing.JButton btnCargarImagen4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAñadir;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
